name: tri-ct-tools
channels:
  - defaults
dependencies:
  - pyyaml
  - pandas
  - matplotlib
  - numpy
  - scipy
  - python
  - pillow
  - tifffile
  - jupyter
  - ipympl
prefix: C:\Users\rikvolger\anaconda3\envs\tri-ct-tools
