name: tri-ct-tools
channels:
  - defaults
dependencies:
  - pyyaml
  - conda-forge::conda-build
  - pandas
  - matplotlib
  - numpy
  - scipy
  - python
  - pillow
  - tifffile
  - conda-forge::jupyter
  - ipympl
  - pip
  - pip:
    - pre-commit
prefix: C:\Users\rikvolger\anaconda3\envs\tri-ct-tools
